#!/bin/sh
umask 022
PID=/run/touchegg.pid
CMD="/usr/bin/touchegg"
OPTS="--daemon"

set -e
test -x $CMD || exit 0

case "$1" in

  start)
    start-stop-daemon --start --quiet --pidfile $PID \
        --exec $CMD -- $OPTS
    ;;
  stop)
    start-stop-daemon --stop --quiet --pidfile $PID
    ;;
  *)
    echo "Usage: /etc/init.d/touchegg {start|stop}"
    exit 1
esac
